### ISSUE TITLE
Forward time leakage in v9 when scaling by max(?)

### ISSUE THREAD

**Issue by SteveBronder** [tvladeck/covid-rt#3]
Creepin on the Stan code, for [here](https://github.com/tvladeck/covid-rt/blob/master/stan_models/rt-v9-just-reporting-error.stan#L34) when you scale by the max of tests

```stan
  for(s in 1:states) {
    for(t in 1:timesteps) {
      if(tests[t, s] > 0) {
        real scaled_tests = tests[t, s] / max(tests[, s]); // Here
        real mutest = fmax(scaled_tests, .1);
        cases[t, s] ~ neg_binomial_2(mutest .* exp(lambda[t, s]), tau[3]);
      }
    }
  }
```

`tests[t, s] / max(tests[, s])` can take the max at each `t` for `T > t`. I haven't ran you code but would `log` or `log1p` suffice to scale for you here? Else you could do something like

```
real scaled_tests = tests[t, s] / max(tests[1:t, s]); 
```

**Comment by tvladeck** [comment]
hi steve, so the idea is that what we're seeing is a "thinned" distribution. e.g some % of actual cases get observed. that % is unobserved directly, but we assume that it is proportional to the number of tests that were given. 

so, this does leak back in time, since we want to adjust the observed cases in the past by the fact that we were undertesting back then. the idea is that if we had 100 tests today and 50% tested positive, and then 1000 tomorrow and 50% tested positive, this model will adjust the first day's inferred case count upward as this model is suggesting that we were undertesting on the first day

**Comment by SteveBronder** [comment]
Thanks Thomas! The scaling makes sense but I think letting each time period peer into the future still seems a bit odd. I was talking with a friend about this yesterday and was wondering if you tried forecasting tests, then you can take the max of 1:t and however far out you'd like to forecast. Then you can account for the upward increase in cases from the increase in tests without peeking

**Comment by tvladeck** [comment]
Actually -- that's awesome, that is the direction I'm going -- take a look here:

https://github.com/tvladeck/covid-rt/blob/master/stan_models/case-curve-rolling-and-deaths.stan

The "peeking" thing doesn't really bother me as much in this case because the model is going to be doing smoothing, not filtering, in any case -- it's going to be taking advantage of the full time series to fit the parameters. 

Would you be interested in talking about this more? We're trying to back into the "true" number of cases, accounting for changes in the testing regime -- tom@gradientmetrics.com

**Comment by SteveBronder** [comment]
Nice! I apologize but I have a lot on my plate right now with Stan stuff so idt I'll have time. But if you don't mind I can cc you and a friend of mine that is doing related work

For the peeking I'd check out this article by Zak David that gives some insights into the bias that can happen. I think even with smoothing you'll still run into this

https://content.iospress.com/articles/algorithmic-finance/af190900

**Comment by SteveBronder** [comment]
Also `to_vector` in params and transformed params makes a copy 

```stan
    expected_cases[, s]  = exp(lambda[, s]) .* to_vector(tests[, s]);
```
It's actually better to do a for loop instead of calling to_vector here
